# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-octo-carnival',
                'doc_host': 'https://banksonian.github.io',
                'git_url': 'https://github.com/banksonian/nbdev-octo-carnival',
                'lib_path': 'nbdev_octo_carnival'},
  'syms': {'nbdev_octo_carnival.core': {'nbdev_octo_carnival.core.foo': ('core.html#foo', 'nbdev_octo_carnival/core.py')}}}